const TermsCondition = () => {
    return (
        <section className="terms-of-service">
            <div className="container">
                <div className="text-center">
                    <h5>Terms of Service</h5>
                </div>
                <p>This document outlines the terms and conditions under which our company, Abracadabra, provides access to our subscription service using third-party AI language models to assist students in
                    writing AI generated essays. By using our service, you agree to be bound by these terms and conditions. If you do not agree to these terms, please do not use our service
                </p>

                <h6> Use of the Service</h6>
                <p>Our service is intended to be used as a tool to assist students in writing the first draft of an essay. It is not intended to be used for any illegal or unethical purposes, including plagiarism or
                    cheating. If you are caught using our service for such purposes, we will not be held liable.</p>

                <h6>Subscription and Cancellation</h6>
                <p>Our service is offered on a subscription basis. You may cancel your subscription at any time through the Account page listed on the website. Please note that we do not offer refunds for any
                    unused portions of your subscription or for any previous periods. However, you will continue to have access to the service until the end of the term for which you have paid</p>

                <h6>Liability</h6>
                <p>Our service is provided as is and utilises third-party software providers, as such, we make no warranties or guarantees regarding the accuracy or reliability of the output generated by the
                    service. We will not be held liable for any errors or omissions in the output, or for any actions taken by you or any third party based on the output generated by the service</p>

                <h6> Changes to the Terms of Service</h6>
                <p>
                    We reserve the right to modify these terms at any time. Any changes to the terms will be posted on this page and will become effective immediately upon posting. It is your responsibility to
                    review these terms regularly to stay informed of any changes. Your continued use of the service after any changes to the terms have been posted will constitute your acceptance of the modified
                    terms
                </p>

                <h6>Governing Law</h6>
                <p>
                    These terms and your use of the service shall be governed by and construed in accordance with the laws of the United Kingdom. Any disputes arising out of or in connection with these terms or
                    the service shall be subject to the exclusive jurisdiction of the courts of the United Kingdom.
                </p>
            </div>
        </section>
    )
}

export default TermsCondition